"""initial migration

Revision ID: 263700247f69
Revises: ec62dc3fbb7b
Create Date: 2021-06-21 18:11:14.341837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263700247f69'
down_revision = 'ec62dc3fbb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'content')
    # ### end Alembic commands ###
