"""initial migration

Revision ID: 920177dff0b8
Revises: 263700247f69
Create Date: 2021-06-22 07:57:26.919792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920177dff0b8'
down_revision = '263700247f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('blog', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_blog_title', table_name='blog')
    op.create_index(op.f('ix_blog_name'), 'blog', ['name'], unique=False)
    op.drop_column('blog', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_blog_name'), table_name='blog')
    op.create_index('ix_blog_title', 'blog', ['title'], unique=False)
    op.alter_column('blog', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('blog', 'name')
    # ### end Alembic commands ###
